version: "3"
services:
  db:
    container_name: api_tidosos
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=tidosos
      - POSTGRES_DB=data
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - "4001:4001"
    working_dir: /
    volumes:
      - "./src:/src"
      - "./config/entrypoint-dev.sh:/entrypoint.sh"
    entrypoint: ["/entrypoint.sh"]
